version: '3'
services:
  game-server:
    container_name: game-server
    build:
      context: ./
      dockerfile: docker-GameServer.Dockerfile
    ports:
      - "2567:2567"
    environment:
      - NODE_ENV=production
  tournaments:
    container_name: tournament-web
    build:
      context: ./tournaments
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production