version: '3'
services:
  game-server:
    container_name: game-server
    build:
      context: .
      dockerfile: ./server/Dockerfile
    ports:
      - "2567:2567"
    environment:
      - NODE_ENV=production
    command: npm run start
  tournament-web:
    container_name: tournament-web
    build:
      context: .
      dockerfile: ./tournaments/Dockerfile
    ports:
      - "2567:2567"
    environment:
      - NODE_ENV=production
    command: npm run start